[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

dependencies = []

[project]
name = "PyQtPaint"
version = "0.1.0"

[tool.setuptools]
packages = ["PyQtPaint"]